spring.application.name=webshop
server.port=2004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d6v6bpffte5s73dm7570-a.oregon-postgres.render.com/veebipood_database_uyxi
spring.datasource.username=veebipood_user
spring.datasource.password=BDBvjMRjCmTXGq6w4l9f9B9RYXiwxTPu